# MongoDB Connection
spring.data.mongodb.uri=mongodb://localhost:27017/syncspace
spring.data.mongodb.database=syncspace

# To help with debugging during development
logging.level.org.springframework.data.mongodb.core.MongoTemplate=DEBUG

# JWT Configuration
jwt.secret=4a6f686e446f655365637265744b65794a575431323334353637383930313233
jwt.expiration=86400000

server.error.include-stacktrace=never
server.error.include-message=never
server.error.include-binding-errors=never 