spring.data.mongodb.uri=mongodb+srv://raunakwarrier2005_db_user:Raunak2005@syncspace-cluster.mi6igcd.mongodb.net/syncspace?retryWrites=true&w=majority
jwt.secret=4a6f686e446f655365637265744b65794a57543132333435363738393030313233
jwt.expiration=86400000
allowed.origins=https://syncspace-omega.vercel.app,http://localhost:3000
server.error.include-stacktrace=never
server.error.include-message=never
server.error.include-binding-errors=never
server.port=10000
