# MongoDB Atlas connection
spring.data.mongodb.uri=${SPRING_DATA_MONGODB_URI}

# JWT
jwt.secret=${JWT_SECRET}

jwt.expiration=86400000

# Error handling
server.error.include-stacktrace=never
server.error.include-message=never
server.error.include-binding-errors=never

# Port (Render sets this automatically)
server.port=${PORT:8080}